apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TdVbdTxVXQ5OCEdQTR0Mn+D/YoVGuXZAV7HlRlH631LE0RRD4Qxm0gQMAomYzuXcYNCqZuYJvOzuHSxOQYBkYWciljSwZ98ZlwmHtIIas8Gi0kP9fawoeqwPw7jWGLWW2qgl4zCEGYg6sQ3KKvFOJmlLOcIb2deLp2+rTxaPgwnIvywLh0gPPG0ZxU6OHm6IKjfyrXWcWTlkreZ9Z1m0GtD9ALcJXdRLMQTOrlOUkpNREPiSDqyspwyVCZJ4qw6Q3p0BlQSu81wq4FOkSLTmq7BWVlq4+VZnI9LJR+NL4PsiJPrdm3FSGVbK7STJH+JPASt1x+OBeYVjPGQvmyldeaepSym8lrlYLqwUslWEFHxV1TM6XC3VeFUQXbUPHPwF,iv:mT+zeys/kRObePat0FKMHU/NZGiqpE8lyXpichyLkHY=,tag:uJ+nxUrSPqmErRV3dTN9oA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Rg7cN07IDXjTsn4m7CjvMFVIutCUhTPTgGlR50/YIZtzHVFHFls7Z/OhC3mE89HoaNvzBKgFPnhBmPIO8n7e3mWMpS8aPwqNNJ2YW7b82Vm8OEt3kvtPUMwRzT19IcdAmjePKs7xkuq7O/8STsF2i9Vq7dN3KJTKd1Z27NG5W4gWHkvBCp0zx1CK7SaDbSQzAc71ggFTyp8m3dq3yMMBmn5Zl1pNaFEF7qFovSw79IhmxkLCVHKphCVPrGukwrObdI600FUthRKuf8JJGA==,iv:r9UYvwFwjt97a8LobSB41HmgH8vvF+O/uAdt72+ZIOs=,tag:o6zni90fOoiOrDzKzi/0TQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:W+uHQCwWGd+ltfZ1hcuXCQr4kS/sFZfiIUiPSA3NEvYdsWnwD3McvRMAxiRHKCj5YDWoxGTRuB7qUqe9c68GCD6hoJGgheVzNKmogdtqkdD/e3HGZYgipUaQYdW6lBFHpfv0XE033DCrCPwbJkVhRdx2RVDrBaF+2l9QN/LijbpG6vbdyPy1Xu+kZo7HHOVCjDvn22MCMdoQVy4mfQIAgw6HISoLH3f4HA7U,iv:knygE9pSMFq7rduq6n8AU4nIO7HLMsaGvQhbCCzdL0Q=,tag:k8byZpHC8f9yIirVuVhiwQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSnZZUTl0cCtzYkU1NENC
            MnNhSGFWb3FKZUExRUtSZzdCNzhkZjVOV3pNCm1mNDhSVWlnYzJBU3U5OE91WVlw
            S284dFl0aWNCT2dDeHBoeGpoQkNTdWsKLS0tIFdyUFFpVk9zejZKS2FUR0JWRVdK
            UkpZa3hGZnBRMTNCMmJ3T05JR1lhTjAKfN998N0LOcYIEAABQJxSXkeJPz5q11w/
            OUJR1nm5W3SkE7HRL27+YUwpIdHd/0A7Uu/AyHD+FCFtQDx3NyfDnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T17:07:29Z"
    mac: ENC[AES256_GCM,data:/RVQEZ5+1sUn1lRTL5Ml4kDTghCkbHJW2Eptpy9nchdGPLojrsTJJmRc4O+DZOhv8TQ0hXz7w5bfiqCha3Y5Jk+ml63Ngo9l/q+Q+atmC8Tu3GcXvd6L8eiFLoEmZuYNBAZk1SYIywguUhK9oHMGvGbUWyNk0jOOoBFLZdGXOGk=,iv:Bm5nKxYyoofA+TgPQ1DXOa1S9mtlWLAb9SvT8iCJLy0=,tag:WEO1Q6rEC1Mks2D9NrdrHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
