apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zNhmg5twzR3psZl1Ar1LSH7y8LJxf9XQl7SoBFmXf4WKKb5wCJyzBmCUnYOHtTq3KkSaaXRRqkTU+MJDyTA/ww/9s1P7CjMUiR7LWmRjg52nNfMejU88z3jN2DQccYRH90r5QHWYkTv2oMQcOEDkhRSWheySVeJTVbrSqr7+AfIy+Xfed768Bw8Gmv+/u7zdcYh/NZDTesYvZ6EQgFLNF4qyfeE03k1MVozsc+kJZzSjqDMtII0ceIyzgAXHBwkhtoac72Zp14ydRbsLFmPvH60xjVifOVwxJaao+9cSTGwBtYmNEAGZfa5563iogtk04yYl8GAMjB+9+wDCkar2qwF2jy63s5yDzkbL/jLbdU2v7x/lx9KMMVKIPDOydSHE,iv:E/I1dWiAPK+WBOZQijoAnhZiL338X3LosLD+Xj32CNo=,tag:esMvUMVvk1Tzs2iM7al6HQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:6ftJZyHN2m2EvGFLooiObdrODap5mtMpmcHD1HVcP1ZJMcyVqWofLAKC4iCgm6XlssBzXWzSGtVg+cQSN3lxUO1nl3+8/4pIgX+pGB52z1mIQfqj5NjKCaP3YUVKzDn58q3vQS3dgExga3r6Edy2nrCdfE15k7gtJ4sbmAOVHBG0qXo/JXTudUfmUt8joa2Qzo3QVhKziP6JkdDS/sa0En2Nw0bBYZOYEeVv+2ZwkMh496NAfoU+Iza/328tVM0h880kks6mZUGNwgbrHA==,iv:V9boPe7heM0e4g3s4rkNUT/+mP/hDuqa8qeCEPnbijs=,tag:TsC47OV3JtNEdF4VpXdELw==,type:str]
    known_hosts: ENC[AES256_GCM,data:M1IG01m8yqyveu16Tq/OwJWwVjCg6JR2uPDR1+mUhPYQvnNgllvbQLLkuAKRf8Ulv+55noU3Y2cJl2wvh7JOYuGCmCnfcNcFr0Bz1OEQIJs5y8VVBrRatI/XZiFWgThIs5JqC5mYClToU2hZV2rkEmE6f/aDmSTkc7qdUEX1mccQzUjnY3R3kGMNSmu+aJa4Dv2gyjzKQphiQey5apaxgwmHtYod/IJjpUay,iv:wChCTpf8/FScMkRX2IAqVOp8bMGUng4eIfy4jWuk7bo=,tag:PCy05/31NKkJn/T35YXfRw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYVZKTUdDcE9mVnh2cnFI
            dldQSGhQTHFTNmduR3lsSm5DUkhlWmgyY2h3Cm5XaWpvVy82NkNRSlBBQ0ZkczJG
            dUY2dnl2bmJNZXduZzY0UzRTb1BvcUUKLS0tICtvKzhMNk5MdjFPZEg2cWZ2UDl4
            MmdYUmJmS1hsRnIrVkRhbHVPQnhxQk0KWHcoDLZWmZQm5KLTPCAaYnx+51/1rF1S
            ttlZo1AZgavSBpwF6bH1ndCBGQ4hhLJ8/qLkIku6CPqjt9w9GqH6lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-17T13:21:07Z"
    mac: ENC[AES256_GCM,data:oLYzsCsAPEMEtim57JKFZJl8RgGX9EqpdCBAXxLrTk1Gy0f3GXfs0JA7GvdOGX4/AXEJi1k4+aPsOAF/7Hq38xAoamWOvU056f2TWM7sFJfShgpC9DTmXetoKBsfgVTRx5PZljrr1xmrtPzaJLjbF7KW4X9zrcJVYLSDFGuIkyM=,iv:E3ehrmspUFSIGCGKhBsqXziUkFh+2bz1CNg/xJRbVck=,tag:t/dceR6Vna/eVOYi9AGUIw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
