apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:or8SY4uLkwu4Fu7JZxNMNIfcGMeN7zb/x2u5D1EZfDMNCp7D8lB/iZMgExDBxJefXAGuSqAzzl3GVtU7JkMXBK/JaJ466/JY1Eoz/OteXZqHswt7er/fNSUPIjUjjbCdXVvBvyHB8Y28VKovh+lHTiHbsvZv2lTxCRWgP+qMnCulYCa3UJAddFJ9+GiqE9Wo0Zvu2IEZ6mBR7HQM9TI/9ORTQfU9d99fMIoxSwtcKeQdeRxDfXNHL7CvabLJYktAkimQ6MyurB664UZe7wXSbaNH9OrXJ0QUyoa9O8PlQ9rjvNipyOUN1JG6Tje/nmqogEHaJADdyPbfGdY5hHlexlH9DajL4dkP+PPKidAACwDgaW1x9nojnR/1eM644k+p,iv:mP3kHgEMnrp+p/5sAGSTZACIUHYb4BnQLwzwhRyXaOs=,tag:nbOHGAH38q/AN+/p58LueA==,type:str]
    identity.pub: ENC[AES256_GCM,data:klI1Xk9UNsK/bafLJiIeuS+KluYVv/P/R0CJl26iEQ+WcHyisfXlVV4qQUgjonZ/ENc3kp4gOmhXEl/Xhp1Wtq0TABADJ0gLWENq6Nf2DXgO694cltUl8W3zfcd29HOGEjgXJKAbmA7BOLyrZQalsbIkLbq59a58IEeUz/SmDxQyDgd4F+LQmlQBKfjpJruumD58R1JW02d7MYs4FhH/JiHgERG+i80b29twYWSGtNs+97Q++lmp6b6X+WKp5dtilkZRo+6p6BSRsU1o5g==,iv:GzVoTG72NCZqYEVSmypmrmFRf92OYUW5IB2R2tuPzE0=,tag:cnIzmTwTxiGLfD/6YqQkOQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:EPCtYR60v3/uWy2b9/8tYfWHlCOP6+1LOcIvtS2pW86Z/EDwl3rHHIGN3q6EaIZmGy5rYnAAGzLAUPXQj9LDPmkF+hROwgUdTybjkqbrDk31ji8MJRwFlAl49KZwkd853gYo6M6VBLSXjvvtJO/ZR+Bcvu7IxhLx6hXFa7Uy27WDEDo7s0QEGqZaRy8tOF1TlYzpWjb1CwyLPaC4pSE/xXPkax+UMmgZVe2A,iv:6jG6EDpqlRw7IHq9Onal1VXJEl+YoQBQ8A1RZGfqYzo=,tag:4FrXC2nVtFCgXOjnd+KvWw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQzExU3Nnd0toWis0b25s
            WkFqZ3NPdk04V0xJNEoxWWw3S1lab2FzbEFNCnh5anhSY3MwUGprQy9LNnFMQ3RW
            c2k1WjZnTUFuTXZWY093bmFhN1g2akkKLS0tIG4zWHo1eUp6Uk52ajFYNFQ3TzNo
            dXlCMm02UTUwOTQxaVpWTlZ4bzMySFkKMQi8xqblPGigylCCiM/pkMCjH/skLyLE
            ljIRVXp5dcNAsb6pFSKeLkhBsoS6eXrmghAPACOFUpTgYLKJE8mNlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-16T15:27:05Z"
    mac: ENC[AES256_GCM,data:8/G82VGwTcuYUZ560CJINInOwZVdFjgjhArxCkOcIybMVTAysRmFkz5MYOOK/g5puBLrFs1XmzZ7Y5BidocLye3TfadDmbgj20GUrz9aiqqH3kZ1HdWa3D9blV2wsN5/q30ZIvfpEcmZTQeAvQksCbFyV34LShvyRRkLAm/LpZc=,iv:e+W4GXxctdbmMRbxzPv6woaPLhQMvNa3btoP4VdiKZA=,tag:uxzAEnzAyRtsmuET4X9S6A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
