apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qZucpVdxZFKmP3lMPA9b+evvs5S8203fInrpvdfpeqOqp5RO3F4z2/BGWIDzG3CoFkboxz9JAFtISlkMNHsdBWnGKlPlIVmcQB01jJGHO5Uh5m6pskc0FB1bXg3wYZrmLrd1e1NVczO24jN1ji60hsJ2kltG95q8XGkjeQjrW61+x+2saqfjZz4jvaYlI9oSjfV9TuoieVHY4GXp3ka++sT0LUN78pedyC1dGgaaINIVWEnOzuz+gkzYCMHkA/OzraMLEjFGEAaQd9aYyESjNZOWOmILBMykB7k1uSwOaJ6LRbPR7rK+9dWyqGbkOQDRWsVM4KdxPCQxCXZGw8kN12pNUuMGSUxxLHbX8VD2RJpjdFkCZ+yQ/xV7837e2RV9,iv:cis3GqSRhumKw3cohfWMNoQ+FEujSQDiHrVavm1oOpE=,tag:uHTWZ+KbyIPHPJPsjk4wQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3dP8ad/Os1gKQN+GJ/Cw/rZ3Ku1c9j+l68nF6+VdcrVauTC12wBXxgWyqCMQgnuf+icbTceVSBXAeXLijZeyRL/UvzcHUYFDzuEUaFCTlUvjoFhsMnCFAG2AQTMvRbTVLpmpSZqcOAJQ4yGB3Yqm29JMntGyJ9cGq9d1HYeLwt273Hgn7ujWyqgZV6kGOxQPr6wty+4SZjOw9gsZdKmmDsU5ClaD1hmUk08dL8dEpn+gyEFCa8L60a0A6ttS1CtvZmw2y0aoPHWBGemT6A==,iv:NP/Nh6ouyaxSpndV5QNkEI9XfiaUW0J/TvC82Xk8guI=,tag:rKtNo2rwsTar0VgqlsNIRQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:xbs6BUHmRjsbF007rfxACWU9RWTWmLgDQTBAUbXWqRcjVqF3BW4IUsOdppIcmLRP8pTnmPbj60oAVguBCgEFpuiBu+I31hrH4qv2qPlypvpRunpfk0sE0N0S6ksBpx4N6hUI1siZDM12Hqb6uSB4GF7Lp1AXd7yQVuzb+GMpOVfuTA1gVZGlbls2z+xs8IZKglybiRuQ1tSV3I50MPkZ2rMnGIPq+W7jDWQR,iv:Ks6QhyHR4ZBS1BASmb5CXWD+qgU9G9XRPrAf+yJJCWw=,tag:X8RHEXLBCVOfaor7fibucw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTzZad09sNDRicWhiaFkw
            R3lXckk3NmVGUklUeUhCQWttVjlyRTd6MUVNClRrVUtHYy93M0JaNnZBdjd3YUVU
            djFjT2FtSmF3UG4zaEJoOWx4cHorQ28KLS0tIHZ5ZXRWZ2FGYlRtNW1KdlZhL1Aw
            MzlRVUxzZFVvYlo2bEd6M0pheFNlb28KlOVL8PQ0BriHtlx/MWuc2NfAvGvcMRb5
            HClBwSJGlCgMPzxn6ba9Z9uxI49r6vxvINuIbXoWE3EimSuM5u+I2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T08:33:37Z"
    mac: ENC[AES256_GCM,data:5+vCZtsPWM5jC/TT+ZA326ea4gyOphWXEVF6kOZqPQ8Rkz5sha4qM5ndynS/0wCPkKlBSPD6CmOnr+zu9GsD2/yDGZaQ2nvbHoZA2u+aB6+cib/F4WYBT1glrAy7CCE2Ble+M82WS+eway29ZQk6N0dpIyHMi1cw4p3tGiz2IH0=,iv:G87NA4PVxLS/XJ0jZeLyZjamWfsM5VagXqDSJBCafas=,tag:zZmS8FRxOiAfX0uCmELBjQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
